spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: root
    driverClassname: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false